package com.github.Duankan.po;

import java.io.Serializable;

public class PermissionPo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionName
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    private String permissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.roleid
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionName
     *
     * @return the value of permission.permissionName
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionName
     *
     * @param permissionname the value for permission.permissionName
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.roleid
     *
     * @return the value of permission.roleid
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.roleid
     *
     * @param roleid the value for permission.roleid
     *
     * @mbggenerated Sat Sep 08 15:34:13 GMT+08:00 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}