package com.github.Duankan.po;

import java.io.Serializable;

public class RolePo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.userid
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param rolename the value for role.roleName
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.userid
     *
     * @return the value of role.userid
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.userid
     *
     * @param userid the value for role.userid
     *
     * @mbggenerated Sat Sep 08 15:33:18 GMT+08:00 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}