package com.github.Duankan.po;

public class TestPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.email
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.addr
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.email
     *
     * @return the value of test.email
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.email
     *
     * @param email the value for test.email
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.addr
     *
     * @return the value of test.addr
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.addr
     *
     * @param addr the value for test.addr
     *
     * @mbggenerated Tue Sep 11 16:50:04 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}