package com.github.Duankan.po;

import java.io.Serializable;

/**
 * 用于shiro权限的usrs实体
 */
public class UsersPo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userName
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.passWord
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userName
     *
     * @return the value of users.userName
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userName
     *
     * @param username the value for users.userName
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.passWord
     *
     * @return the value of users.passWord
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.passWord
     *
     * @param password the value for users.passWord
     *
     * @mbggenerated Sat Sep 08 15:31:40 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}