package com.github.Duankan.dao;

import com.github.Duankan.po.GitPo;

public interface GitPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Thu Oct 04 17:43:22 GMT+08:00 2018
     */
    int insert(GitPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Thu Oct 04 17:43:22 GMT+08:00 2018
     */
    int insertSelective(GitPo record);
}