package com.github.Duankan.dao;

import com.github.Duankan.po.TestPo;

public interface TestPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    int insert(TestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    int insertSelective(TestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    TestPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    int updateByPrimaryKeySelective(TestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Sep 25 09:09:54 CST 2018
     */
    int updateByPrimaryKey(TestPo record);
}