package com.github.Duankan.dao;

import com.github.Duankan.po.UserPo;

public interface UserPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    int insert(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    int insertSelective(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    UserPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 08 15:23:40 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserPo record);

    UserPo queryById(Integer id);
}